#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:topjava_boot_graduation
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:topjava
    # Absolute path
    #    url: jdbc:h2:C:/projects/bootjava/db/topjava
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/db/topjava
    # Relative path form current dir
    #    url: jdbc:h2:./db/topjava
    # Relative path from home
    #    url: jdbc:h2:~/topjava
    #    tcp: jdbc:h2:tcp://localhost:9092/~/topjava
    username: sa
    password:

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
#    cache-names: users
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: WARN
    ru.javaops.topjava: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

springdoc.swagger-ui.path: /
